function [fitresult, gof] = createFit(eps_soft, bs_term)
%CREATEFIT(EPS_SOFT,BS_TERM)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : eps_soft
%      Y Output: bs_term
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Sep-2017 12:22:40


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( eps_soft, bs_term );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'bs_term vs. eps_soft', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel eps_soft
ylabel bs_term
grid on


